sulanguage: python

python:
  - 3.5

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

script:
  - pyrcc5 -o kontrollblatt_sh/resources_rc.py kontrollblatt_sh/resources.qrc

jobs:
  include:

# Deploy on tag
    - stage: deploy
      if: tag is present
      script: plugin_ci/release/release.sh